"""Initial migration

Revision ID: 04009d44ea44
Revises: 1b8d27892130
Create Date: 2026-02-11 20:40:41.328249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04009d44ea44'
down_revision = '1b8d27892130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yoga_pose', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yoga_pose', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
